# Generated by Django 4.2.6 on 2023-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
    ]
